apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: "{{ .Release.Namespace }}"
data:
  DISCORD_OAUTH2_LINK: https://discord.com/api/oauth2/authorize?client_id=571839826744180736&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2Fauth&response_type=code&scope=identify%20guilds%20guilds.members.read
  HOST: localhost
  DEV: false
