apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}-deployment"
  name: "{{ .Release.Name }}-service"
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: "{{ .Release.Name }}-deployment"
